### ISSUE TITLE
Stable Diffusion Trainer

### ISSUE THREAD

**Issue by gvalvano** [keras-team/keras-cv#887] opened 2022-10-06 13:36 UTC
Hi, thanks for this excellent work! :) 

Do you plan to share a trainer for the stable diffusion model?

**Comment by LukeWood** [comment] 2022-10-06 15:44
As an API probably not.

As a fine tuning tutorial - definitely!

**Comment by gvalvano** [comment] 2022-10-06 17:26
Cool! I think it would be super-useful to let people understand better how to replicate these experiments.
I'm looking forward to it!

**Comment by tanzhenyu** [comment] 2022-10-13 16:57
> Cool! I think it would be super-useful to let people understand better how to replicate these experiments. I'm looking forward to it!

I think we should provide some training script, in general all KerasCV models should have reproducible result and we aim to achieve paper-claimed SOTA metrics, though external contribution welcome as we don't have immediate plans for it.

**Comment by LukeWood** [comment] 2022-10-18 16:02
@tanzhenyu I think this is probably out of scope for the package in that it would cost 800K to retrain.

Maybe useful in our fine-tuning journey, but in the meantime maybe we just keep this in a keras.io tutorial?  WDYT?

**Comment by tanzhenyu** [comment] 2022-10-18 16:05
> @tanzhenyu I think this is probably out of scope for the package in that it would cost 800K to retrain.
> 
> Maybe useful in our fine-tuning journey, but in the meantime maybe we just keep this in a keras.io tutorial? WDYT?

We can't reproduce the exact results for Stable Diffusion, I agree. Though a training script on a smaller dataset might be reasonable ask, but we might not have the bandwidth to achieve that.

**Comment by LukeWood** [comment] 2022-10-18 16:30
> > @tanzhenyu I think this is probably out of scope for the package in that it would cost 800K to retrain.
> > Maybe useful in our fine-tuning journey, but in the meantime maybe we just keep this in a keras.io tutorial? WDYT?
> 
> We can't reproduce the exact results for Stable Diffusion, I agree. Though a training script on a smaller dataset might be reasonable ask, but we might not have the bandwidth to achieve that.

Lets just host this in the tutorial itself for now then evaluate promotion to a component afterwards.  I have a draft of the trainer available in: https://github.com/keras-team/keras-io/pull/1088

**Closed by LukeWood** 2022-10-18 16:30 UTC
Labels: keras-team-review-pending
