### ISSUE TITLE
Exception: URL fetch failure on https://huggingface.co/fchollet/stable-diffusion/resolve/main/kcv_encoder.h5: None -- [Errno 11002] getaddrinfo failed

### ISSUE THREAD

**Issue by VERISBABY** [keras-team/keras-cv#1950] opened 2023-07-14 12:32 UTC
My internet connection is fine but i don't know why this error happen when i test this basic code:
```
import keras_cv
from PIL import Image
model = keras_cv.models.StableDiffusion(jit_compile=True)
image = model.text_to_image('a cat', batch_size=1)

Image.open(image)
```

Full traceback:
```
gaierror                                  Traceback (most recent call last)
File [c:\Program](file:///C:/Program) Files\Python311\Lib\urllib\request.py:1348, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1347 try:
-> 1348     h.request(req.get_method(), req.selector, req.data, headers,
   1349               encode_chunked=req.has_header('Transfer-encoding'))
   1350 except OSError as err: # timeout error

File [c:\Program](file:///C:/Program) Files\Python311\Lib\http\client.py:1286, in HTTPConnection.request(self, method, url, body, headers, encode_chunked)
   1285 """Send a complete request to the server."""
-> 1286 self._send_request(method, url, body, headers, encode_chunked)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\http\client.py:1332, in HTTPConnection._send_request(self, method, url, body, headers, encode_chunked)
   1331     body = _encode(body, 'body')
-> 1332 self.endheaders(body, encode_chunked=encode_chunked)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\http\client.py:1281, in HTTPConnection.endheaders(self, message_body, encode_chunked)
   1280     raise CannotSendHeader()
-> 1281 self._send_output(message_body, encode_chunked=encode_chunked)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\http\client.py:1041, in HTTPConnection._send_output(self, message_body, encode_chunked)
   1040 del self._buffer[:]
-> 1041 self.send(msg)
   1043 if message_body is not None:
   1044 
...
--> 351         raise Exception(error_msg.format(origin, e.errno, e.reason))
    352 except (Exception, KeyboardInterrupt):
    353     if os.path.exists(fpath):

Exception: URL fetch failure on https://huggingface.co/fchollet/stable-diffusion/resolve/main/kcv_encoder.h5: None -- [Errno 11002] getaddrinfo failed
```

**Comment by ianstenbit** [comment] 2023-07-17 16:50
Hi @VERISBABY -- this issue looks like it's unrelated to KerasCV. I'm not able to reproduce it, and I've verified that this weights link is valid.

By the error message, this may be a transient issue, or may be due to a DNS configuration issue on your end (which may not clearly manifest itself in normal web browsing)

I'm going to close this issue as it appears KerasCV is WAI

**Closed by ianstenbit** 2023-07-17 16:50 UTC
