### ISSUE TITLE
KERAS_CV : YOLOV8 loading and predict method after custom training and saving. 

### ISSUE THREAD

**Issue by marionpavaux** [keras-team/keras-cv#2043] opened 2023-08-29 12:26 UTC
Hello, I am experiencing an issue with YOLOV8 loading after training and saving. I am creating the model as below, fit it with my dataset, save it and then try to load it to test its deployment. 

```python
backbone = keras_cv.models.YOLOV8Backbone.from_preset("yolo_v8_xs_backbone")
yolo = keras_cv.models.YOLOV8Detector(
        num_classes=len(CLASS_MAPPING),
        bounding_box_format="xywh",
        backbone=backbone,
        fpn_depth=1,
    )
optimizer = tf.keras.optimizers.Adam(
        learning_rate=LEARNING_RATE,
        global_clipnorm=GLOBAL_CLIPNORM,
    )
yolo.compile(optimizer=optimizer, classification_loss="binary_crossentropy", box_loss="ciou")
training_history = yolo.fit(
        training_dataset,
        validation_data=val_dataset,
        epochs=N_EPOCHS,
        callbacks=[
            EvaluateCOCOMetricsCallback(val_dataset, os.path.join(MODELS_PATH, ID, "model.h5")),
            keras.callbacks.EarlyStopping(monitor='loss', patience=3, restore_best_weights=True, verbose=1),
        ],
    )
```

My problem is that I can load the model using the `.keras ` extension, but when I am trying to predict, an error occurs saying that DictWrapper object is not subscriptable. (I verified that the validation set predicted during the fitting phase and the one with loaded model had the same format). 

I then tried to save and load my model with  the `.h5 ` or `.tf ` extension, with or without precising the `custom_object_scope` context, and this is the error I got : 

```python
with keras.saving.custom_object_scope({"keras_cv": keras_cv.models.YOLOV8Detector, "keras_cv.models": keras_cv.models.YOLOV8Backbone}):
        yolo.save(os.path.join(MODELS_PATH, ID, "model.h5"))
        loaded_model = tf.keras.saving.load_model(os.path.join(MODELS_PATH, ID, "model.h5"), custom_objects={"keras_cv": keras_cv.models.YOLOV8Detector, "keras_cv.models": keras_cv.models.YOLOV8Backbone})

ValueError: Unknown layer: 'YOLOV8Detector'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
```

### Version:
- Keras_cv version: 0.6.1
- Tensorflow version: 2.13.0

Thanks for your insights !

**Comment by sampathweb** [comment] 2023-08-29 19:14
Can you create a Colab with some dummy data to reproduce the issue so its easier to take a look and help.

**Comment by marionpavaux** [comment] 2023-08-30 15:52
Yes sure no problem, here is the link : https://colab.research.google.com/drive/1X-Gg4vKJcn-YMn_hfiqdyEkWhsFYwiLP?usp=sharing

**Comment by henrisve** [comment] 2023-09-11 18:02
Looks like your custom_objects is incorrect. This works for me:
```
yolo = keras.saving.load_model(filename,
              custom_objects={
                        "YOLOV8Detector": keras_cv.models.YOLOV8Detector,
                        "YOLOV8Backbone": keras_cv.models.YOLOV8Backbone)
                             },
               compile=False)
```

**Comment by divyashreepathihalli** [comment] 2023-12-16 01:49
closing because there seems to be a resolution.

**Closed by divyashreepathihalli** 2023-12-16 01:49 UTC
Labels: bug
