### ISSUE TITLE
`pytest` fails on CPU due to `SimCLRTrainerTest`

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1364] opened 2023-02-06 23:07 UTC
Our test suite does not run on CPU due to `SimCLRTrainerTest.test_train_without_probing`. Is this something we could fix to enable CPU-based development?

```sh
E     tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__MakeIterator_device_/job:localhost/replica:0/task:0/device:CPU:0}} No OpK
ernel was registered to support Op 'AdjustContrastv2' used by {{node sim_clr_augmenter/maybe_apply_1/map/while/body/_273/sim_clr_augmenter/maybe_apply_1/map/while/cond/
then/_1048/sim_clr_augmenter/maybe_apply_1/map/while/cond/random_color_jitter/random_contrast/adjust_contrast}} with these attrs: [T=DT_HALF]
E     Registered devices: [CPU]
E     Registered kernels:
E       device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_HALF]
E       device='CPU'; T in [DT_FLOAT]
E       device='GPU'; T in [DT_HALF]
E       device='GPU'; T in [DT_FLOAT]
E       device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_HALF]
E     
E        [[sim_clr_augmenter/maybe_apply_1/map/while/body/_273/sim_clr_augmenter/maybe_apply_1/map/while/cond/then/_1048/sim_clr_augmenter/maybe_apply_1/map/while/cond/
random_color_jitter/random_contrast/adjust_contrast]] [Op:MakeIterator]

../../.pyenv/versions/3.10.0/envs/keras-cv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py:7215: InvalidArgumentError
```

**Comment by bhack** [comment] 2023-02-07 12:22
Who is going to enable jit/XLA compilation in this test?

As generally we don't have tests/decorators for a systematic coverage of the components/models in this library.

**Comment by jbischof** [comment] 2023-02-08 00:16
@bhack apologies I'm sure not I understand your comment. Are you asking for additional functionality? Is this related to GPU-only ops? XLA can run on CPU

**Comment by bhack** [comment] 2023-02-08 00:26
I meant where this is failing? On which test? Has the test enabled jit_compile or is it is hard coded in the implementation?

Cause generally we don't have a compile decorator for testing compilation in the library on components.

**Comment by jbischof** [comment] 2023-02-08 00:59
I don't think this is related to XLA, but maybe I'm missing something. The test is [here](https://github.com/keras-team/keras-cv/blob/8245576207f0cde34f0a1bb502eadf2dbe2a640a/keras_cv/training/contrastive/simclr_trainer_test.py#L24).

**Comment by jbischof** [comment] 2023-02-08 01:02
cc @ianstenbit, who developed this code

**Comment by ianstenbit** [comment] 2023-02-08 02:54
Based on the error message, it seems like somehow there's a mixed-precision policy being used here which is causing the failure. It looks like the kernel exists for `DT_FLOAT`, just not for `DT_HALF`.

**Comment by ianstenbit** [comment] 2023-02-08 02:54
I've reproduced this locally and found that it's fixed by #1371

**Comment by bhack** [comment] 2023-02-08 03:19
Oh it was from another test. 
Probably it is better to handle this with fixture, teardown etc..

**Comment by jbischof** [comment] 2023-02-08 03:37
Apologies @ianstenbit maybe I misread the console barf! Thanks for the fix

**Closed** 2023-02-08 04:04 UTC
Labels: bug
