### ISSUE TITLE
BUG: KerasCV on Google Colab

### ISSUE THREAD

**Issue by DavidLandup0** [keras-team/keras-cv#582] opened 2022-07-13 08:55 UTC
There seems to be an installation/import issue on Colab:

https://colab.research.google.com/drive/1Rym9hVppHB52CiAB2jBvdFZCVcns2U-j?usp=sharing

KerasCV can't seem to import layers from the main TensorFlow package.

**Comment by quantumalaviya** [comment] 2022-07-13 11:45
I think it's because KerasCV requires TF 2.9+

https://keras.io/keras_cv/

**Comment by DavidLandup0** [comment] 2022-07-13 11:50
> I think it's because KerasCV requires TF 2.9+
> 
> https://keras.io/keras_cv/

It does, but so does KerasNLP and it works on install on Cokab. The correct TF version should probably be packaged as a dependency of KerasCV, hence I opened the issue :)

**Comment by DavidLandup0** [comment] 2022-07-13 11:51
And I misclicked and closed it 🤦‍♂️

**Comment by bhack** [comment] 2022-07-13 12:13
It Is a duplicate of https://github.com/keras-team/keras-cv/issues/442

**Comment by LukeWood** [comment] 2022-07-13 16:19
We can't update Colab's TensorFlow version from the KerasCV end.  Colab will lag a bit on this and that is to be expected.  Sorry for any inconvenience :(.

No action item from KerasCV, so closing.

**Closed by LukeWood** 2022-07-13 16:19 UTC
