### ISSUE TITLE
`requirements.txt` required

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras-cv#489] opened 2022-06-14 11:55 UTC
Currently, the project does not have a `requirements.txt` file as in the core Keras repo. The current "Setup environment" section in CONTRIBUTING.md does not provide a good support for the same.

It would be great to have a requirements.txt as well as clear instructions for setting up the dev environment. Along with that it might be worthwhile to include versions for the formatters as well.

**Comment by bhack** [comment] 2022-06-14 12:02
Probably it is a semi-duplicate of https://github.com/keras-team/keras-cv/issues/442

**Comment by LukeWood** [comment] 2022-06-14 18:50
> Currently, the project does not have a `requirements.txt` file as in the core Keras repo. The current "Setup environment" section in CONTRIBUTING.md does not provide a good support for the same.
> 
> It would be great to have a requirements.txt as well as clear instructions for setting up the dev environment. Along with that it might be worthwhile to include versions for the formatters as well.

Can we resolve all of these issues with the “install_requires” of our setup.py?

**Comment by qlzh727** [comment] 2022-10-21 21:00
I think there are value to have a separate requirements.txt so that people can configure the local env without pip install keras CV (if they want to update keras cv code from github download).

We just need to make sure the information are sync between those different files.

Fow now, can we just https://github.com/keras-team/keras-cv/blob/master/cloudbuild/requirements.txt?

**Comment by ianstenbit** [comment] 2023-08-04 16:53
We now have a requirements.txt

**Closed by ianstenbit** 2023-08-04 16:53 UTC
Labels: enhancement, low-priority
