### ISSUE TITLE
Difference to MaP and upstream pycocotools metrics

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#684] opened 2022-08-11 18:25 UTC
Area range happens after matching/before, this can make a numerical difference.  Line reference:

https://github.com/keras-team/keras-cv/blob/master/keras_cv/metrics/coco/mean_average_precision.py#L237

**Comment by LukeWood** [comment] 2022-08-11 18:29
Can be either fixed or just documented in the white paper

**Comment by tanzhenyu** [comment] 2022-10-27 16:54
Closing this as duplicate of https://github.com/keras-team/keras-cv/issues/915

**Closed by tanzhenyu** 2022-10-27 16:55 UTC
